FROM debian:12

ENV NODE_ENV "production"
ENV SALTCORN_DISABLE_UPGRADE "true"

RUN apt update && apt install -qqy libpq-dev build-essential python-is-python3 postgresql-client git chromium npm nodejs

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD "true"

RUN npm install -g @saltcorn/cli@0.9.5-beta.26 --unsafe

ENTRYPOINT ["/usr/local/bin/saltcorn"]