FROM debian:buster
ENV 

# dependencies
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
  apt-get -y install \
  build-essential \
  nodejs sqlite3 libsqlite3-dev libpq-dev

RUN npm install -g saltcorn-cli

RUN which saltcorn

ENV PATH "$PATH:/opt/saltcorn/packages/saltcorn-cli/bin/saltcorn"

ENTRYPOINT ["/opt/saltcorn/packages/saltcorn-cli/bin/saltcorn"]