version: "2"

services:
  app:
    image: saltcorn/saltcorn
    entrypoint: "/wait-for-it.sh database:5432 -- saltcorn serve"
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    ports:
      - "3000:3000"
    env_file:
      - .env
  database:
    image: postgres:13-alpine
    volumes:
      - ./docker-entrypoint-initdb.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - "POSTGRES_USER=${PGUSER}"
      - "POSTGRES_PASSWORD=${PGPASSWORD}"
      - "POSTGRES_DB=${PGDATABASE}"
