FROM node:16

WORKDIR /opt/saltcorn

COPY . /opt/saltcorn

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD "true"
ENV SALTCORN_DISABLE_UPGRADE "true"

RUN npm install --legacy-peer-deps
RUN npm run tsc

ENV PATH "$PATH:/opt/saltcorn/packages/saltcorn-cli/bin/saltcorn"

ENTRYPOINT ["/opt/saltcorn/packages/saltcorn-cli/bin/saltcorn"]