ARG NODE_BASE_IMAGE=18
FROM node:${NODE_BASE_IMAGE}

ARG SALTCORN_VERSION=1.1.3

ENV HOME=/home/node
ENV NPM_CONFIG_PREFIX=${HOME}
ENV NODE_ENV="production"

ENV SALTCORN_DISABLE_UPGRADE="true"

WORKDIR ${HOME}

RUN npm install -g @saltcorn/cli@1.1.3 --omit=dev && \
    mkdir -p ${HOME} && \
    chown -R 1000:0 ${HOME} && \
    chmod -R g+w ${HOME} && \
    chmod -R g=u ${HOME}

ENTRYPOINT ["bin/saltcorn"]