deb13_node24:
  image: debian/13
  runtime: incus
  disable: true
  command:
    - apt update -q
    - wget -qO - https://deb.nodesource.com/setup_24.x | bash -
    - apt-get install -qqy nodejs
    - adduser someuser
    - sudo -iu someuser npx -y saltcorn-install -y -n
    - systemctl is-active saltcorn
    - wget -qO- http://localhost/ | grep Please 

deb13_node24a:
  image: debian/13
  runtime: incus
  command:
    - cat /etc/passwd
    