apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "saltcorn.fullname" . }}-pvc
  labels:
    app: {{ include "saltcorn.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClassName }}
