// variables.js

module.exports = {
    GoBack: 'GoBack',
    Delete: 'Delete',
    List: 'List',
    viewForTable: 'view for table',
    NewView: 'NewView',
    vieweditNew: 'viewedit/new',
    createView: 'Create view',
    viewEdit: 'viewedit',
    inputType: 'View',
    inputTextValue: 'my view',
    pageName: 'MyPage',
    placeholderText: 'Testing the placeholder',
    inputTypeValue: 'Page',
    textSettings: 'Text settings',
    textToDisplay: 'Text to display',
    sidebarMenuText: 'Menu',
    viewPageUrl: 'view/NewView',
    pagePageUrl: 'page/MyPage',
    myViewText: 'my view',
    myPageText: 'MyPage',
    addButtonMenuText: 'Add',
    testPageName: 'TestPage',
    cardTitleText: 'Hello',
    Library : 'library',
    textPlaceholder: 'Hello World',
    nameField: 'Name Field',
    myCard: 'mycard',
    testPage: 'TestPage',
    library: 'Library',
    list: 'list',
    tags: 'Tags',
    tag: 'tag',
    mytag : 'my tag',
    createTag: 'Create tag',
    addViews: 'Add views',
    newView: 'NewView',
    addPages: 'Add pages',
    myPage: 'MyPage',
    diagram: 'Diagram',
    diagramUrl: 'diagram',


  };
  