# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"

  config.ssh.forward_agent = true

  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
    vb.memory = "4096"
  end

  config.vm.provision "shell", inline: <<-SHELL

    set -e
    sudo apt update -q
    wget -qO - https://deb.nodesource.com/setup_22.x | bash -
    apt install -qqy nodejs libpq-dev build-essential python-is-python3 postgresql postgresql-client fail2ban git libcap2-bin unattended-upgrades libsystemd-dev chromium python3-pip python3.11-venv
    sudo -iu postgres psql -U postgres -d template1 -c 'create extension if not exists "uuid-ossp";'

    sudo -iu postgres createdb saltcorn 
    sudo -iu postgres createdb saltcorn_test
    sudo -iu postgres psql -U postgres -c "ALTER USER postgres WITH PASSWORD 'foobar';"
    sudo -iu vagrant mkdir -p /home/vagrant/.config/

    cat <<EOF > /home/vagrant/.config/.saltcorn
    {
        "host":"localhost",
        "port":5432,
        "database":"saltcorn",
        "user":"postgres",
        "password":"foobar",
        "session_secret":"jjtrjtyjd",
        "multi_tenant": true
    }
EOF
    echo '127.0.0.1 example.com sub.example.com sub1.example.com sub2.example.com sub3.example.com sub4.example.com sub5.example.com' | sudo tee -a /etc/hosts
    echo '127.0.0.1 otherexample.com' | sudo tee -a /etc/hosts
    chown vagrant:vagrant /home/vagrant/.config/.saltcorn
    chmod 600 /home/vagrant/.config/.saltcorn
    sudo -iu vagrant git clone https://github.com/saltcorn/saltcorn.git
    echo 'export PATH=/home/vagrant/saltcorn/packages/saltcorn-cli/bin:$PATH' >> /home/vagrant/.bashrc
    sudo -iu vagrant bash -c "cd saltcorn && git checkout fix-pytest"   
    sudo -iu vagrant bash -c "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true cd saltcorn && npm install --legacy-peer-deps && npm install --legacy-peer-deps && npm run tsc"   
    sudo -iu vagrant bash -c "python3 -m venv .env"
    sudo -iu vagrant bash -c ".env/bin/pip install requests pytest pyotp python-socketio[client]"
    sudo -iu vagrant bash -c "cd saltcorn && ~/.env/bin/pytest infosec-scan/"
    sudo -iu vagrant bash -c "SQLITE_FILEPATH=/tmp/db cd saltcorn && packages/saltcorn-cli/bin/saltcorn run-tests saltcorn-data"
    sudo -iu vagrant bash -c "SQLITE_FILEPATH=/tmp/db cd saltcorn && packages/saltcorn-cli/bin/saltcorn run-tests server"
  SHELL
end

#then:

# git clone https://github.com/saltcorn/saltcorn.git
# git checkout <branch>
# packages/saltcorn-cli/bin/saltcorn run-tests

    