/* eslint-disable no-console */
/**
 * Code generator for ./generated_tags.ts
 *
 * The HTML tag helpers exported by ./tags are derived from the `html-tags`
 * package. In a CommonJS world these could be built dynamically at runtime
 * (Object.fromEntries over html-tags). Under ESM there is no way to create
 * named exports dynamically, so we generate a module with one explicit named
 * export per tag instead.
 *
 * The generated file is checked into git and is the source of truth for the
 * build (`tsc --build` does not run npm lifecycle scripts). Re-run this script
 * with `npm run gen:tags` whenever the `html-tags` dependency changes; it also
 * runs automatically before the package's own `npm run tsc` (via `pretsc`).
 */
"use strict";

const fs = require("fs");
const path = require("path");
const htmlTags = require("html-tags");
const voidHtmlTags = require("html-tags/void");

const voidSet = new Set(voidHtmlTags);

// JS reserved words cannot be used as a binding name, so they cannot be a
// `export const <name>`. They are still valid as an export *name* via an
// aliased export (`export { foo as <name> }`) and as object property keys.
const RESERVED = new Set([
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "enum",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "function",
  "if",
  "import",
  "in",
  "instanceof",
  "new",
  "null",
  "return",
  "super",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "var",
  "void",
  "while",
  "with",
  "yield",
  "await",
  "let",
  "static",
]);

const isIdent = (s) => /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(s);

const tags = [...htmlTags].sort();
for (const tag of tags) {
  if (!isIdent(tag))
    throw new Error(
      `html tag ${JSON.stringify(tag)} is not a valid identifier`
    );
}

const localName = (tag) => (RESERVED.has(tag) ? `${tag}_` : tag);

const constLines = tags.map((tag) => {
  const args = voidSet.has(tag) ? `"${tag}", true` : `"${tag}"`;
  const voidNote = voidSet.has(tag) ? " // void element" : "";
  if (RESERVED.has(tag))
    // reserved word: bind to a safe local name and re-export under the tag name
    return `const ${localName(tag)} = mkTag(${args});\nexport { ${localName(tag)} as ${tag} };${voidNote}`;
  return `export const ${tag} = mkTag(${args});${voidNote}`;
});

// Every tag is a valid identifier (checked above), so it is also a valid
// unquoted property key — even reserved words like `var`.
const allTagsEntries = tags
  .map((tag) =>
    RESERVED.has(tag) ? `  ${tag}: ${localName(tag)},` : `  ${tag},`
  )
  .join("\n");

const unionLines = tags.map((tag) => `  | "${tag}"`).join("\n");

const out = `// ---------------------------------------------------------------------------
// AUTO-GENERATED FILE — DO NOT EDIT.
//
// Generated by gen-tags.js (\`npm run gen:tags\`) from the \`html-tags\` package.
// To change the set of HTML tag helpers, update the html-tags dependency and
// regenerate. See gen-tags.js for details.
// ---------------------------------------------------------------------------
/**
 * @category saltcorn-markup
 * @module generated_tags
 */
import mkTag from "./mktag";
import type { TagFunction } from "./types";

${constLines.join("\n")}

/** All generated HTML tag helpers keyed by tag name. */
export const allTags: { [k: string]: TagFunction } = {
${allTagsEntries}
};

/** Union of every generated HTML tag name. */
export type GeneratedTagName =
${unionLines};
`;

const target = path.join(__dirname, "generated_tags.ts");
fs.writeFileSync(target, out);
console.log(
  `Wrote ${tags.length} tags to ${path.relative(process.cwd(), target)}`
);
