// ---------------------------------------------------------------------------
// AUTO-GENERATED FILE — DO NOT EDIT.
//
// Generated by gen-tags.cjs (`npm run gen:tags`) from the `html-tags` package.
// To change the set of HTML tag helpers, update the html-tags dependency and
// regenerate. See gen-tags.cjs for details.
// ---------------------------------------------------------------------------
/**
 * @category saltcorn-markup
 * @module generated_tags
 */
import mkTag from "./mktag.js";
import type { TagFunction } from "./types.js";

export const a = mkTag("a");
export const abbr = mkTag("abbr");
export const address = mkTag("address");
export const area = mkTag("area", true); // void element
export const article = mkTag("article");
export const aside = mkTag("aside");
export const audio = mkTag("audio");
export const b = mkTag("b");
export const base = mkTag("base", true); // void element
export const bdi = mkTag("bdi");
export const bdo = mkTag("bdo");
export const blockquote = mkTag("blockquote");
export const body = mkTag("body");
export const br = mkTag("br", true); // void element
export const button = mkTag("button");
export const canvas = mkTag("canvas");
export const caption = mkTag("caption");
export const cite = mkTag("cite");
export const code = mkTag("code");
export const col = mkTag("col", true); // void element
export const colgroup = mkTag("colgroup");
export const data = mkTag("data");
export const datalist = mkTag("datalist");
export const dd = mkTag("dd");
export const del = mkTag("del");
export const details = mkTag("details");
export const dfn = mkTag("dfn");
export const dialog = mkTag("dialog");
export const div = mkTag("div");
export const dl = mkTag("dl");
export const dt = mkTag("dt");
export const em = mkTag("em");
export const embed = mkTag("embed", true); // void element
export const fieldset = mkTag("fieldset");
export const figcaption = mkTag("figcaption");
export const figure = mkTag("figure");
export const footer = mkTag("footer");
export const form = mkTag("form");
export const h1 = mkTag("h1");
export const h2 = mkTag("h2");
export const h3 = mkTag("h3");
export const h4 = mkTag("h4");
export const h5 = mkTag("h5");
export const h6 = mkTag("h6");
export const head = mkTag("head");
export const header = mkTag("header");
export const hgroup = mkTag("hgroup");
export const hr = mkTag("hr", true); // void element
export const html = mkTag("html");
export const i = mkTag("i");
export const iframe = mkTag("iframe");
export const img = mkTag("img", true); // void element
export const input = mkTag("input", true); // void element
export const ins = mkTag("ins");
export const kbd = mkTag("kbd");
export const label = mkTag("label");
export const legend = mkTag("legend");
export const li = mkTag("li");
export const link = mkTag("link", true); // void element
export const main = mkTag("main");
export const map = mkTag("map");
export const mark = mkTag("mark");
export const math = mkTag("math");
export const menu = mkTag("menu");
export const menuitem = mkTag("menuitem", true); // void element
export const meta = mkTag("meta", true); // void element
export const meter = mkTag("meter");
export const nav = mkTag("nav");
export const noscript = mkTag("noscript");
export const object = mkTag("object");
export const ol = mkTag("ol");
export const optgroup = mkTag("optgroup");
export const option = mkTag("option");
export const output = mkTag("output");
export const p = mkTag("p");
export const param = mkTag("param", true); // void element
export const picture = mkTag("picture");
export const pre = mkTag("pre");
export const progress = mkTag("progress");
export const q = mkTag("q");
export const rb = mkTag("rb");
export const rp = mkTag("rp");
export const rt = mkTag("rt");
export const rtc = mkTag("rtc");
export const ruby = mkTag("ruby");
export const s = mkTag("s");
export const samp = mkTag("samp");
export const script = mkTag("script");
export const search = mkTag("search");
export const section = mkTag("section");
export const select = mkTag("select");
export const slot = mkTag("slot");
export const small = mkTag("small");
export const source = mkTag("source", true); // void element
export const span = mkTag("span");
export const strong = mkTag("strong");
export const style = mkTag("style");
export const sub = mkTag("sub");
export const summary = mkTag("summary");
export const sup = mkTag("sup");
export const svg = mkTag("svg");
export const table = mkTag("table");
export const tbody = mkTag("tbody");
export const td = mkTag("td");
export const template = mkTag("template");
export const textarea = mkTag("textarea");
export const tfoot = mkTag("tfoot");
export const th = mkTag("th");
export const thead = mkTag("thead");
export const time = mkTag("time");
export const title = mkTag("title");
export const tr = mkTag("tr");
export const track = mkTag("track", true); // void element
export const u = mkTag("u");
export const ul = mkTag("ul");
const var_ = mkTag("var");
export { var_ as var };
export const video = mkTag("video");
export const wbr = mkTag("wbr", true); // void element

/** All generated HTML tag helpers keyed by tag name. */
export const allTags: { [k: string]: TagFunction } = {
  a,
  abbr,
  address,
  area,
  article,
  aside,
  audio,
  b,
  base,
  bdi,
  bdo,
  blockquote,
  body,
  br,
  button,
  canvas,
  caption,
  cite,
  code,
  col,
  colgroup,
  data,
  datalist,
  dd,
  del,
  details,
  dfn,
  dialog,
  div,
  dl,
  dt,
  em,
  embed,
  fieldset,
  figcaption,
  figure,
  footer,
  form,
  h1,
  h2,
  h3,
  h4,
  h5,
  h6,
  head,
  header,
  hgroup,
  hr,
  html,
  i,
  iframe,
  img,
  input,
  ins,
  kbd,
  label,
  legend,
  li,
  link,
  main,
  map,
  mark,
  math,
  menu,
  menuitem,
  meta,
  meter,
  nav,
  noscript,
  object,
  ol,
  optgroup,
  option,
  output,
  p,
  param,
  picture,
  pre,
  progress,
  q,
  rb,
  rp,
  rt,
  rtc,
  ruby,
  s,
  samp,
  script,
  search,
  section,
  select,
  slot,
  small,
  source,
  span,
  strong,
  style,
  sub,
  summary,
  sup,
  svg,
  table,
  tbody,
  td,
  template,
  textarea,
  tfoot,
  th,
  thead,
  time,
  title,
  tr,
  track,
  u,
  ul,
  var: var_,
  video,
  wbr,
};

/** Union of every generated HTML tag name. */
export type GeneratedTagName =
  | "a"
  | "abbr"
  | "address"
  | "area"
  | "article"
  | "aside"
  | "audio"
  | "b"
  | "base"
  | "bdi"
  | "bdo"
  | "blockquote"
  | "body"
  | "br"
  | "button"
  | "canvas"
  | "caption"
  | "cite"
  | "code"
  | "col"
  | "colgroup"
  | "data"
  | "datalist"
  | "dd"
  | "del"
  | "details"
  | "dfn"
  | "dialog"
  | "div"
  | "dl"
  | "dt"
  | "em"
  | "embed"
  | "fieldset"
  | "figcaption"
  | "figure"
  | "footer"
  | "form"
  | "h1"
  | "h2"
  | "h3"
  | "h4"
  | "h5"
  | "h6"
  | "head"
  | "header"
  | "hgroup"
  | "hr"
  | "html"
  | "i"
  | "iframe"
  | "img"
  | "input"
  | "ins"
  | "kbd"
  | "label"
  | "legend"
  | "li"
  | "link"
  | "main"
  | "map"
  | "mark"
  | "math"
  | "menu"
  | "menuitem"
  | "meta"
  | "meter"
  | "nav"
  | "noscript"
  | "object"
  | "ol"
  | "optgroup"
  | "option"
  | "output"
  | "p"
  | "param"
  | "picture"
  | "pre"
  | "progress"
  | "q"
  | "rb"
  | "rp"
  | "rt"
  | "rtc"
  | "ruby"
  | "s"
  | "samp"
  | "script"
  | "search"
  | "section"
  | "select"
  | "slot"
  | "small"
  | "source"
  | "span"
  | "strong"
  | "style"
  | "sub"
  | "summary"
  | "sup"
  | "svg"
  | "table"
  | "tbody"
  | "td"
  | "template"
  | "textarea"
  | "tfoot"
  | "th"
  | "thead"
  | "time"
  | "title"
  | "tr"
  | "track"
  | "u"
  | "ul"
  | "var"
  | "video"
  | "wbr";
