# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/kinetic64"

  config.ssh.forward_agent = true

  config.ssh.insert_key = false

  config.vm.provision "shell", inline: <<-SHELL
    set -e
    wget -qO - https://deb.nodesource.com/setup_16.x | bash -
    apt-get install -qqy nodejs
    sudo -iu vagrant npx -y saltcorn-install -y
    systemctl is-active saltcorn
    wget -qO- http://localhost/ | grep Please   
  SHELL
end
